export const academyCourses = [
  {
    title: "Practical Accounting Training & Coaching",
    desc: "A comprehensive program to build practical accounting knowledge and professional skills — from foundational bookkeeping to advanced financial reporting.",
    items: [
      { label: "Junior Accountant Program" },
      { label: "Accountant Program" },
    ],
    outcomes: [
      "Bookkeeping fundamentals",
      "Journal entries & ledgers",
      "Bank reconciliation",
      "Financial statement preparation",
      "Payroll basics",
    ],
    image: "/assets/academy-course-practical.jpg",
    icon: { paths: ["M4 20V4h16v16z", "M8 8h8M8 12h8M8 16h5"] },
  },
  {
    title: "Accounting Software Courses",
    desc: "Hands-on training on the accounting platforms businesses use every day.",
    items: [
      { label: "QuickBooks", logo: "/assets/tools/quickbooks.svg" },
      { label: "Tally ERP 9", logo: "/assets/tools/tallyerp9.png" },
      { label: "Tally Prime", logo: "/assets/tools/tallyprime.png" },
      { label: "Xero", logo: "/assets/tools/xero.svg" },
      { label: "Zoho Books", logo: "/assets/tools/zoho.svg" },
      { label: "Sage 50", logo: "/assets/tools/sage.svg" },
    ],
    outcomes: [
      "Company setup",
      "Chart of Accounts",
      "VAT management",
      "Financial reporting",
      "Bank reconciliation",
    ],
    image: "/assets/academy-course-software.jpg",
    icon: { paths: ["M4 4h16v13H4z", "M9 20h6", "M12 17v3", "M8 8h5", "M8 11h8"] },
  },
  {
    title: "MS Excel Programs",
    desc: "Practical Excel skills for accounting, reporting, and data analysis.",
    items: [
      { label: "MS Excel (Basic to Advanced)", logo: "/assets/tools/excel.svg" },
    ],
    outcomes: [
      "Create professional reports",
      "Master Pivot Tables",
      "Advanced formulas (XLOOKUP, INDEX)",
      "Data validation",
      "Dashboard creation",
    ],
    image: "/assets/academy-course-excel.jpg",
    icon: { paths: ["M4 4h16v16H4z", "M4 9h16M9 4v16"] },
  },
  {
    title: "Additional Software Skills",
    desc: "Everyday business software skills to support reporting and productivity.",
    items: [
      { label: "MS Word", logo: "/assets/tools/word.svg" },
      { label: "MS PowerPoint", logo: "/assets/tools/powerpoint.svg" },
      { label: "MS Access", logo: "/assets/tools/access.svg" },
      { label: "Power BI", logo: "/assets/tools/powerbi.svg" },
    ],
    outcomes: [
      "Professional documents & reports",
      "Impactful presentations",
      "Database management basics",
      "Data visualization & dashboards",
      "Business reporting techniques",
    ],
    image: "/assets/academy-course-additional.jpg",
    icon: { paths: ["M4 4h6v6H4z", "M14 4h6v6h-6z", "M4 14h6v6H4z", "M14 14h6v6h-6z"] },
  },
];
