export const services = [
  {
    slug: "accounting",
    name: "Accounting",
    tagline: "Accurate records. Better insights. Smarter decisions.",
    icon: { paths: ["M6 3h12v18H6z", "M9 7h6M9 11h6M9 15h4"] },
    problems: [
      "Missing or inaccurate records",
      "Tax filing and compliance issues",
      "Cash flow uncertainty",
      "Lack of financial visibility",
    ],
    solutions: [
      "Bookkeeping & Accounting",
      "Financial Statements",
      "Bank Reconciliation",
      "Management Reporting",
    ],
    benefits: [
      "Better decision making",
      "Audit ready records",
      "Improved cash flow",
      "Business growth visibility",
    ],
    timeline: "Ongoing",
  },
  {
    slug: "taxation",
    name: "Taxation",
    tagline: "Stay compliant and minimize your tax burden.",
    icon: { paths: ["M6 3h9l3 3v15H6z", "M15 3v3h3", "M9 12h6M9 16h6"] },
    problems: [
      "Missed filing deadlines",
      "Complex tax regulations",
      "Risk of penalties",
      "Poor tax planning",
    ],
    solutions: [
      "Tax Return Filing",
      "VAT & Compliance",
      "Tax Planning & Advisory",
      "Regulatory Liaison",
    ],
    benefits: [
      "Full compliance",
      "Reduced tax liability",
      "Peace of mind",
      "Accurate submissions",
    ],
    timeline: "2-4 weeks",
  },
  {
    slug: "payroll",
    name: "Payroll",
    tagline: "Accurate, on-time payroll every cycle.",
    icon: {
      paths: [
        "M9 11a3 3 0 100-6 3 3 0 000 6z",
        "M4 20c0-3 2.5-5 5-5s5 2 5 5",
        "M16 8h4M16 12h4M16 16h4",
      ],
    },
    problems: [
      "Manual salary errors",
      "Late payments",
      "Compliance risks",
      "No employee self-service",
    ],
    solutions: [
      "Payroll Processing",
      "Statutory Filings",
      "Payslip Generation",
      "EPF/ETF Management",
    ],
    benefits: [
      "On-time payments",
      "Zero compliance risk",
      "Happier employees",
      "Time saved",
    ],
    timeline: "Ongoing",
  },
  {
    slug: "business-support",
    name: "Business Support",
    tagline: "Operational support so you can focus on growth.",
    icon: {
      paths: [
        "M9 6V4a2 2 0 012-2h2a2 2 0 012 2v2",
        "M3 8h18v11a2 2 0 01-2 2H5a2 2 0 01-2-2V8z",
        "M3 12h18",
      ],
    },
    problems: [
      "Admin overload",
      "No dedicated support",
      "Scaling challenges",
      "Disorganized operations",
    ],
    solutions: [
      "Business Advisory",
      "Process Setup",
      "Admin Support",
      "Growth Planning",
    ],
    benefits: [
      "More time to focus on core business",
      "Streamlined operations",
      "Scalable systems",
      "Expert guidance",
    ],
    timeline: "Ongoing",
  },
  {
    slug: "software-solutions",
    name: "Software Solutions",
    tagline: "Modern tools for accurate, real-time finance.",
    icon: {
      paths: ["M4 4h16v13H4z", "M9 20h6", "M12 17v3", "M8 8h5", "M8 11h8"],
    },
    problems: [
      "Outdated systems",
      "Manual data entry",
      "No real-time visibility",
      "Integration issues",
    ],
    solutions: [
      "Software Implementation",
      "Cloud Accounting Setup",
      "Automation Tools",
      "Staff Training",
    ],
    benefits: [
      "Real-time reporting",
      "Fewer errors",
      "Time savings",
      "Scalable systems",
    ],
    timeline: "3-6 weeks",
  },
  {
    slug: "corporate-services",
    name: "Corporate Services",
    tagline: "End-to-end company formation and governance.",
    icon: { paths: ["M4 21V9l8-6 8 6v12", "M9 21v-6h6v6", "M4 9h16"] },
    problems: [
      "Complex incorporation process",
      "Regulatory uncertainty",
      "Governance gaps",
      "Documentation delays",
    ],
    solutions: [
      "Company Registration",
      "Secretarial Services",
      "Corporate Governance",
      "Regulatory Filings",
    ],
    benefits: [
      "Faster setup",
      "Full legal compliance",
      "Reduced risk",
      "Ongoing support",
    ],
    timeline: "2-6 weeks",
  },
  {
    slug: "training-development",
    name: "Training & Development",
    tagline: "Practical training to build future-ready teams.",
    icon: {
      paths: ["M8 3l9 4.5-9 4.5-9-4.5z", "M4 9.5v5c0 2 3.5 4 8 4s8-2 8-4v-5"],
    },
    problems: [
      "Skills gaps in finance teams",
      "Outdated practices",
      "Low staff confidence",
      "Career stagnation",
    ],
    solutions: [
      "Practical Workshops",
      "Certification Courses",
      "Software Training",
      "Career Mentorship",
    ],
    benefits: [
      "Skilled workforce",
      "Higher productivity",
      "Career growth",
      "Certified expertise",
    ],
    timeline: "Ongoing",
  },
];
