export const services = [
  {
    slug: "accounting-bookkeeping",
    name: "Accounting and Bookkeeping",
    intro:
      "We provide accurate accounting and bookkeeping services that ensure businesses meet regulatory compliance in both the UAE and Sri Lanka. From maintaining ledgers to preparing financial statements, we help clients maintain transparency and control. Our team uses updated software aligned with IFRS and local tax rules to deliver timely reporting.",
    icon: { paths: ["M6 3h12v18H6z", "M9 7h6M9 11h6M9 15h4"] },
    features: [
      "Bookkeeping & Accounting",
      "Accounts Payable & Receivable",
      "Bank Reconciliation",
      "Payroll Support",
      "Fixed Asset Management",
      "Inventory Reconciliation",
      "Financial Reporting",
      "Management Reports (MIS)",
      "Month-End Closing",
      "Budgeting & Analysis",
    ],
  },
  {
    slug: "taxation",
    name: "Taxation",
    intro:
      "We provide end-to-end taxation services, including Corporate Tax, VAT (UAE), and Income Tax (Sri Lanka). Our experts ensure accurate tax filings, strategic tax planning, and compliance with evolving laws. We help businesses legally minimize liabilities and avoid penalties while adhering to the latest regulatory requirements in both jurisdictions.",
    icon: { paths: ["M6 3h9l3 3v15H6z", "M15 3v3h3", "M9 12h6M9 16h6"] },
    features: [
      "VAT Registration",
      "VAT Deregistration",
      "VAT Return Filing",
      "VAT Compliance Review",
      "Corporate Tax Registration",
      "Corporate Tax Return Filing",
      "Corporate Tax Compliance Support",
      "Tax Record Maintenance",
      "FTA Portal Assistance",
      "Tax Advisory & Consultation",
      "VAT Refund Assistance",
      "Amendment of Tax Registration Details",
      "Penalty Review & Guidance",
    ],
  },
  {
    slug: "accounting-software-implementation",
    name: "Accounting Software Implementation",
    intro:
      "We provide professional accounting software implementation services to help businesses establish reliable and efficient accounting systems. Our support includes software setup, initial configuration, data migration assistance, and user guidance to ensure a smooth implementation process. We help businesses improve accounting accuracy, streamline financial operations, and enhance reporting capabilities.",
    icon: {
      paths: ["M4 4h16v13H4z", "M9 20h6", "M12 17v3", "M8 8h5", "M8 11h8"],
    },
    features: [
      "Accounting Software Setup & Configuration",
      "Chart of Accounts Setup",
      "Opening Balance Migration",
      "Customer & Supplier Master Setup",
      "Inventory Master Setup",
      "User Access & Role Configuration",
      "Financial Reporting Setup",
      "Data Migration Support",
      "System Testing & Verification",
      "User Training & Guidance",
      "Accounting Process Alignment",
      "Post-Implementation Support",
      "Cloud Accounting System Setup",
      "Business Process Integration",
      "Accounting System Review & Improvement",
    ],
  },
  {
    slug: "corporate-secretary-services",
    name: "Corporate Secretary Services",
    intro:
      "We provide expert corporate secretarial services in Sri Lanka, including company incorporation, statutory filings, maintaining registers, and organizing board meetings. Our services ensure full compliance with the Companies Act and regulations issued by the Registrar of Companies. We help businesses maintain proper governance and avoid legal and regulatory penalties.",
    icon: { paths: ["M4 21V9l8-6 8 6v12", "M9 21v-6h6v6", "M4 9h16"] },
    features: [
      "Company Incorporation Support",
      "Company Registration Assistance",
      "Preparation of Board Resolutions",
      "Maintenance of Statutory Registers",
      "Annual Return Preparation & Filing",
      "Shareholder & Director Record Maintenance",
      "Company Structure Amendments",
      "Change of Directors & Shareholders",
      "Registered Office Address Updates",
      "Corporate Document Preparation",
      "Regulatory Compliance Support",
    ],
  },
  {
    slug: "payroll",
    name: "Payroll",
    intro:
      "We manage the full payroll cycle, salary calculations, WPS processing (UAE), EPF/ETF compliance (Sri Lanka), and employee benefits. Our payroll service ensures confidentiality, accuracy, and compliance with local labor laws. We also provide monthly pay-slips, leave records, and tax or gratuity calculations with minimal administrative burden for clients.",
    icon: {
      paths: [
        "M9 11a3 3 0 100-6 3 3 0 000 6z",
        "M4 20c0-3 2.5-5 5-5s5 2 5 5",
        "M16 8h4M16 12h4M16 16h4",
      ],
    },
    features: [
      "Payroll Processing & Administration",
      "Salary Calculation & Verification",
      "Overtime & Allowance Calculation",
      "Leave Salary Calculation",
      "End of Service Benefits (EOSB) Calculation",
      "Employee Payroll Record Maintenance",
      "Payroll Reporting",
      "WPS File Preparation Support",
      "Payroll Reconciliation",
      "Payroll Compliance Support",
      "New Employee & Exit Payroll Processing",
      "Salary Transfer Schedule Preparation",
      "Monthly Payroll Review & Verification",
      "Payroll Documentation Support",
    ],
  },
  {
    slug: "costing-management-accounting",
    name: "Costing and Management Accounting",
    intro:
      "Our management accounting services support internal decision-making by analyzing cost behavior, product profitability, and operational efficiency. We help businesses in Sri Lanka and the UAE identify cost-saving opportunities, price products effectively, and allocate resources better, ultimately improving performance and driving strategic business decisions.",
    icon: { paths: ["M4 20V10M10 20V4M16 20v-7M22 20V13"] },
    features: [
      "Cost Analysis & Cost Control",
      "Product & Service Costing",
      "Budget Preparation & Monitoring",
      "Budget vs Actual Variance Analysis",
      "Profitability Analysis",
      "Cost Reduction Strategies",
      "Break-Even Analysis",
      "Cash Flow Planning & Monitoring",
      "Management Reporting (MIS)",
      "Financial Performance Analysis",
      "Pricing Strategy Support",
      "Departmental Cost Allocation",
      "Business Performance Measurement",
      "Forecasting & Financial Planning",
      "Decision-Making Support Reports",
    ],
  },
  {
    slug: "fixed-asset-management",
    name: "Fixed Asset Management",
    intro:
      "We maintain comprehensive asset registers, conduct asset tagging, and perform periodic reconciliations to ensure accurate fixed asset accounting. We help clients manage depreciation, impairment, and revaluation in line with IFRS standards and local reporting requirements, ensuring transparency and control over company-owned resources across both markets.",
    icon: {
      paths: [
        "M3 7h18v13a1 1 0 01-1 1H4a1 1 0 01-1-1V7z",
        "M3 7l2-4h14l2 4",
        "M9 12h6",
      ],
    },
    features: [
      "Fixed Asset Register Maintenance",
      "Asset Identification & Classification",
      "Asset Coding & Tagging Support",
      "Asset Acquisition Recording",
      "Depreciation Calculation & Posting",
      "Asset Verification & Physical Count Support",
      "Asset Transfer Tracking",
      "Asset Disposal & Write-Off Management",
      "Asset Reconciliation",
      "Asset Lifecycle Management",
      "Capitalization of Fixed Assets",
      "Fixed Asset Reporting",
      "Asset Movement Monitoring",
      "Fixed Asset Schedule Preparation",
      "Compliance & Documentation Support",
    ],
  },
  {
    slug: "budgeting-forecasting",
    name: "Budgeting and Forecasting",
    intro:
      "We provide tailored budgeting and forecasting services to help businesses set financial goals, anticipate trends, and make data-driven decisions. By analyzing historical data and market trends in Sri Lanka and the UAE, we help companies prepare rolling budgets and financial models aligned with strategic plans and cash flow targets.",
    icon: { paths: ["M3 17l6-6 4 4 8-8", "M15 6h6v6"] },
    features: [
      "Annual Budget Preparation",
      "Monthly & Quarterly Budget Planning",
      "Revenue Forecasting",
      "Expense Forecasting",
      "Cash Flow Forecasting",
      "Budget vs Actual Analysis",
      "Variance Analysis & Reporting",
      "Financial Planning Support",
      "Profitability Forecasting",
      "Departmental Budgeting",
      "Business Performance Monitoring",
      "Scenario & Trend Analysis",
      "Strategic Financial Planning",
      "Cost Planning & Control",
      "Management Reporting & Insights",
    ],
  },
  {
    slug: "consultations",
    name: "Consultations",
    intro:
      "Our expert consultation services guide businesses through financial challenges, operational restructuring, and compliance requirements in the UAE and Sri Lanka. We provide insights on business setup, tax optimization, process improvements, and financial planning to help organizations thrive in dynamic and competitive environments.",
    icon: {
      paths: ["M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"],
    },
    features: [
      "Accounting Consultation",
      "Bookkeeping Consultation",
      "VAT & Corporate Tax Consultation",
      "Business Setup Consultation",
      "Financial Reporting Consultation",
      "Costing & Profitability Consultation",
      "Budgeting & Forecasting Consultation",
      "Fixed Asset Management Consultation",
      "Payroll Consultation",
      "Internal Control & Process Improvement Consultation",
      "Accounting System Consultation",
      "Business Performance Review",
      "Financial Health Check",
      "Compliance & Regulatory Consultation",
      "General Business Advisory Services",
    ],
  },
];
